= How to Even Work on this Website

Welcome to authoring content for the Steel Toe website! When deployed, this website consists of static content generated using the https://gohugo.io[Hugo] framework. Also, we author content using the http://asciidoctor.org/[Asciidoctor] markup format.

== Prerequisites

1. https://gohugo.io/overview/installing/[Install] Hugo.
2. http://asciidoctor.org/docs/install-toolchain/[Install] Asciidoctor.
2. Clone this repo.
3. Get invited as a space developer to the following orgs/spaces on PWS:
+
* Staging: spring.io/steeltoe-staging
* Production: spring.io/steeltoe-production

== Local Development

After you've cloned the repo, execute the following command to run a local dev server that will refresh as you edit content:

----
$ hugo server --theme=github-project-landing-page --buildDrafts
----

You'll have the Steel Toe website running at http://localhost:1313.

== Working on Front Page Sections

The source code for the sections found on the front page are located in `content/post`. The first section is called `first.adoc`, the second `second.adoc`, and so on. There is nothing magical about the names - they are only named that way as a reminder to humans about the order in which they'll appear on the home page.

The magic that creates the ordering is the `weight` attribute found in the header of each file. Lower values appear closer to the top, higher values appear closer to the bottom. Annotate your content according to how you want it to appear.

== Deployment

If you have some changes that you want to deploy to PWS:

1. Make sure you're happy with your changes using the *_Local Development_* instructions.

2. If everything looks good, commit that content and push it to GitHub.

3. A Concourse pipeline will run and deploy your changes to Staging. You can temporarily find this pipeline at http://scs.ci.springapps.io:8080/pipelines/steeltoe-site, which requires Pivotal VPN access, and you must be a member of the SCS team. We'll get it moved soon enough.

4. In a few moments, view your changes at http://steeltoe-stage.cfapps.io.

NOTE: Production deployments aren't currently set up in Concourse. Stay tuned.
